config/locales/en.yml, lib/parliament/grom/decorator.rb, lib/parliament/grom/decorator/person.rb, parliament-grom-decorators.gemspec, spec/spec_helper.rb
* Added I18n language file
* Switched out hard coded strings for I18n equivalent
* Added parliament-ruby gem as a development dependency
=> [WEBSITE-952] Remove hard coded strings to language file

lib/parliament/grom/decorator/party.rb, lib/parliament/grom/decorator/version.rb, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Party/_commons_count/Grom_Node_has_a_Commons_count/returns_the_Commons_count_for_a_Grom_Node_object_of_type_Party.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Party/_commons_count/Grom_Node_has_no_Commons_count/returns_nil.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Party/_current_/Grom_Node_returns_the_correct_value_for_a_current_or_non_current_party.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Party/_lords_count/Grom_Node_has_a_Lords_count/returns_the_Lords_count_for_a_Grom_Node_object_of_type_Party.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Party/_lords_count/Grom_Node_has_no_Lords_count/returns_nil.yml, spec/parliament/grom/decorator/party_spec.rb
* Added commons_count, lords_count and current?
=> [WEBSITE-981] Added new party decorators

lib/parliament/grom/decorator.rb
* Corrected path to translation file
=> [WEBSITE-1212] Fixed I18n loading incorrect translation file

lib/parliament/grom/decorator.rb, lib/parliament/grom/decorator/version.rb
* Load translation files into I18n manually
* Upped version to 0.1.6
=> [WEBSITE-1212] Fixed I18n not loading translation file

parliament-grom-decorators.gemspec, spec/parliament/grom/decorator/parliaments_spec.rb
* Also corrected error in timecop implementation for parliament current spec.
=> [WEBSITE-1317] Updated homepage link in gemspec

lib/parliament/grom/decorator/person.rb, lib/parliament/grom/decorator/version.rb, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Person/_image_id/Grom_Node_does_not_have_an_image_id/returns_by_default_a_placeholder_string_for_a_Grom_Node_object_of_type_Person.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Person/_image_id/Grom_Node_does_not_have_an_image_id/returns_nil_if_show_placeholder_is_overridden.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Person/_image_id/Grom_Node_has_an_image_id/returns_the_image_id_string_for_a_Grom_Node_objects_of_type_Person.yml, spec/parliament/grom/decorator/person_spec.rb
* Add image_id method
* Add tests
* Update version of gem
=> [WEBSITE-1511] Add image id decorator to Person

lib/parliament/grom/decorator.rb, lib/parliament/grom/decorator/formal_body.rb, lib/parliament/grom/decorator/formal_body_membership.rb, lib/parliament/grom/decorator/person.rb, lib/parliament/grom/decorator/version.rb, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_FormalBody/_name/Grom_Node_has_a_name/will_return_correct_name.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_FormalBody/_name/Grom_Node_has_no_name/will_return_an_empty_string.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_FormalBodyMembership/_current_/is_current/will_return_true.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_FormalBodyMembership/_current_/is_not_current/will_return_false.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_FormalBodyMembership/_end_date/Grom_Node_has_an_end_date/will_return_correct_end_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_FormalBodyMembership/_end_date/Grom_Node_has_no_end_date/will_return_nil.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_FormalBodyMembership/_formal_body/has_formal_body/will_return_formal_body.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_FormalBodyMembership/_formal_body/has_no_formal_body/will_return_nil.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_FormalBodyMembership/_start_date/Grom_Node_has_a_start_date/will_return_correct_start_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_FormalBodyMembership/_start_date/Grom_Node_has_no_start_date/will_return_nil.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Person/_formal_body_memberships/Grom_Node_has_all_the_required_objects/returns_the_formal_body_membership_Grom_Node_objects_of_type_Person.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Person/_formal_body_memberships/Grom_Node_has_no_formal_body_memberships/will_return_an_empty_array.yml, spec/parliament/grom/decorator/formal_body_membership_spec.rb, spec/parliament/grom/decorator/formal_body_spec.rb, spec/parliament/grom/decorator/person_spec.rb
* Added FormalBodyMembership
* Added FormalBody
* Updated Person to include a formal body membership
* Added and updated specs
* Bumped the version number
=> Added decorators for a persons formal bodies

lib/parliament/grom/decorator/formal_body.rb, lib/parliament/grom/decorator/version.rb, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_FormalBody/_current_/is_current/will_return_true.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_FormalBody/_current_/is_not_current/will_return_false.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_FormalBody/_end_date/Grom_Node_has_an_end_date/will_return_correct_end_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_FormalBody/_end_date/Grom_Node_has_no_end_date/will_return_nil.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_FormalBody/_start_date/Grom_Node_has_a_start_date/will_return_correct_start_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_FormalBody/_start_date/Grom_Node_has_no_start_date/will_return_nil.yml, spec/parliament/grom/decorator/formal_body_spec.rb
* Added new decorators
* Added specs
* Bumped version
=> Added additional date decorators to FormalBody

lib/parliament/grom/decorator/person.rb, lib/parliament/grom/decorator/version.rb, parliament-grom-decorators.gemspec, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Person/_weblinks/Grom_Node_has_all_the_required_objects/returns_the_correct_link.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Person/_weblinks/Grom_Node_has_all_the_required_objects/returns_the_weblinks_Grom_Node_objects_of_type_Person.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Person/_weblinks/Grom_Node_has_no_weblinks/will_return_nil.yml, spec/parliament/grom/decorator/person_spec.rb
* Added Person#weblinks to bring back an array of their links
* Updated specs
* Bumped version
=> [WEBSITE-1668] Added new decorator for a persons weblinks

lib/parliament/grom/decorator.rb, lib/parliament/grom/decorator/government_incumbency.rb, lib/parliament/grom/decorator/government_position.rb, lib/parliament/grom/decorator/person.rb, lib/parliament/grom/decorator/version.rb, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentIncumbency/_current_/is_current/will_return_true.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentIncumbency/_current_/is_not_current/will_return_false.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentIncumbency/_date_range/government_incumbency_has_an_end_date/returns_full_formatted_start_and_end_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentIncumbency/_date_range/government_incumbency_has_no_end_date/returns_formatted_start_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentIncumbency/_date_range/government_incumbency_has_no_start_date/returns_no_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentIncumbency/_end_date/Grom_Node_has_an_end_date/will_return_correct_end_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentIncumbency/_end_date/Grom_Node_has_no_end_date/will_return_nil.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentIncumbency/_start_date/Grom_Node_has_a_start_date/will_return_correct_start_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentIncumbency/_start_date/Grom_Node_has_no_start_date/will_return_nil.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentPosition/_name/Grom_Node_has_a_name/will_return_correct_name.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentPosition/_name/Grom_Node_has_no_name/will_return_empty_string.yml, spec/parliament/grom/decorator/government_incumbency_spec.rb, spec/parliament/grom/decorator/government_position_spec.rb
* Added decorators for GovernmentIncumbency and GovernmentPosition
* Added tests for GovernmentIncumbency and GovernmentPosition
* Bumped version number
=> [WEBSITE-2027] Added government roles decorators

lib/parliament/grom/decorator/government_incumbency.rb, lib/parliament/grom/decorator/version.rb, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentIncumbency/_current_/is_current/will_return_true.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentIncumbency/_current_/is_not_current/will_return_false.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentIncumbency/_date_range/government_incumbency_has_an_end_date/returns_full_formatted_start_and_end_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentIncumbency/_date_range/government_incumbency_has_no_end_date/returns_formatted_start_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentIncumbency/_date_range/government_incumbency_has_no_start_date/returns_no_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentIncumbency/_end_date/Grom_Node_has_an_end_date/will_return_correct_end_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentIncumbency/_end_date/Grom_Node_has_no_end_date/will_return_nil.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentIncumbency/_start_date/Grom_Node_has_a_start_date/will_return_correct_start_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_GovernmentIncumbency/_start_date/Grom_Node_has_no_start_date/will_return_nil.yml
* Fix government incumbency decorators and cassettes to use incumbencyStartDate rather than parliamentaryIncumbencyStartDate
=> [Fix-government-incumbency]

lib/parliament/grom/decorator.rb, lib/parliament/grom/decorator/opposition_incumbency.rb, lib/parliament/grom/decorator/opposition_position.rb, lib/parliament/grom/decorator/version.rb, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_OppositionIncumbency/_current_/is_current/will_return_true.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_OppositionIncumbency/_current_/is_not_current/will_return_false.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_OppositionIncumbency/_date_range/opposition_incumbency_has_an_end_date/returns_full_formatted_start_and_end_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_OppositionIncumbency/_date_range/opposition_incumbency_has_no_end_date/returns_formatted_start_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_OppositionIncumbency/_date_range/opposition_incumbency_has_no_start_date/returns_no_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_OppositionIncumbency/_end_date/Grom_Node_has_an_end_date/will_return_correct_end_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_OppositionIncumbency/_end_date/Grom_Node_has_no_end_date/will_return_nil.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_OppositionIncumbency/_start_date/Grom_Node_has_a_start_date/will_return_correct_start_date.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_OppositionIncumbency/_start_date/Grom_Node_has_no_start_date/will_return_nil.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_OppositionPosition/_name/Grom_Node_has_a_name/will_return_correct_name.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_OppositionPosition/_name/Grom_Node_has_no_name/will_return_empty_string.yml, spec/parliament/grom/decorator/opposition_incumbency_spec.rb, spec/parliament/grom/decorator/opposition_position_spec.rb
* Added OppositionIncumbency and OppositionRole modules
* Updated specs
* Bumped version
=> Added opposition roles decorators

lib/parliament/grom/decorator.rb, lib/parliament/grom/decorator/article_type.rb, lib/parliament/grom/decorator/audience.rb, lib/parliament/grom/decorator/version.rb, lib/parliament/grom/decorator/web_article.rb, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_ArticleType/_article_type_name/Grom_Node_does_not_have_a_title/returns_an_empty_string.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_ArticleType/_article_type_name/Grom_Node_has_all_the_required_objects/confirms_that_the_type_for_this_Grom_Node_object_is_Article.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_ArticleType/_article_type_name/Grom_Node_has_all_the_required_objects/returns_the_title_of_the_article_the_Grom_Node_object.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Audience/_audience_name/Grom_Node_does_not_have_a_title/returns_an_empty_string.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Audience/_audience_name/Grom_Node_has_all_the_required_objects/confirms_that_the_type_for_this_Grom_Node_object_is_Article.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Audience/_audience_name/Grom_Node_has_all_the_required_objects/returns_the_title_of_the_article_the_Grom_Node_object.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_WebArticle/_related_articles/Grom_Node_does_not_have_any_related_articles/returns_an_empty_array.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_WebArticle/_related_articles/Grom_Node_has_all_the_required_objects/returns_an_array.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_WebArticle/_related_articles/Grom_Node_has_all_the_required_objects/returns_an_array_of_Grom_Nodes.yml, spec/parliament/grom/decorator/article_type_spec.rb, spec/parliament/grom/decorator/audience_spec.rb, spec/parliament/grom/decorator/web_article_spec.rb
* Add additional WebArticle decorator
* Add Audience decorator and test
* Add ArticleType decorator and test
* Bumped up version number to 0.15.0
=> Add WebArticle, Audience, ArticleType decorator and tests

lib/parliament/grom/decorator.rb, lib/parliament/grom/decorator/collection.rb, lib/parliament/grom/decorator/version.rb, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Collection/_collection_name/Grom_Node_does_not_have_a_title/returns_an_empty_string.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Collection/_collection_name/Grom_Node_has_all_the_required_objects/confirms_that_the_type_for_this_Grom_Node_object_is_Article.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Collection/_collection_name/Grom_Node_has_all_the_required_objects/returns_the_title_of_the_article_the_Grom_Node_object.yml, spec/parliament/grom/decorator/collection_spec.rb
* Add decorators and tests
* Bumped up version number to 0.16.0
=> Add Collection decorators

lib/parliament/grom/decorator/person.rb, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Person/_mnis_id/Grom_Node_has_all_the_required_objects/returns_the_mnis_id_for_a_Grom_Node_object_of_type_Person.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Person/_mnis_id/Grom_Node_has_no_mnis_id/returns_nil.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Person/_pims_id/Grom_Node_has_all_the_required_objects/returns_the_pims_id_for_a_Grom_Node_object_of_type_Person.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Person/_pims_id/Grom_Node_has_no_pims_id/returns_nil.yml, spec/parliament/grom/decorator/person_spec.rb
* added pims_id and mnis_id decorators to person.rb
* Added tests for pims_id and mnis_id
=> Added mnis_id and pims_id decorators for person_by_id

lib/parliament/grom/decorator.rb, lib/parliament/grom/decorator/concept.rb, lib/parliament/grom/decorator/person.rb, lib/parliament/grom/decorator/version.rb, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Concept/_child_concepts/Grom_Node_does_not_have_any_child_concepts/returns_an_empty_array.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Concept/_child_concepts/Grom_Node_has_all_the_required_objects/returns_an_array.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Concept/_child_concepts/Grom_Node_has_all_the_required_objects/returns_an_array_of_Grom_Nodes.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Concept/_definition/Grom_Node_does_not_have_a_description/returns_an_empty_string.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Concept/_definition/Grom_Node_has_all_the_required_objects/returns_the_description_of_the_Grom_Node_object.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Concept/_description/Grom_Node_does_not_have_a_description/returns_an_empty_string.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Concept/_description/Grom_Node_has_all_the_required_objects/returns_the_description_of_the_Grom_Node_object.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Concept/_name/Grom_Node_does_not_have_a_title/returns_an_empty_string.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Concept/_name/Grom_Node_has_all_the_required_objects/confirms_that_the_type_for_this_Grom_Node_object_is_Concept.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Concept/_name/Grom_Node_has_all_the_required_objects/returns_the_title_of_the_Grom_Node_object.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Concept/_parent_concepts/Grom_Node_does_not_have_any_parent_concepts/returns_an_empty_array.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Concept/_parent_concepts/Grom_Node_has_all_the_required_objects/returns_an_array.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Concept/_parent_concepts/Grom_Node_has_all_the_required_objects/returns_an_array_of_Grom_Nodes.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Concept/_tagged_articles/Grom_Node_does_not_have_any_tagged_articles/returns_an_empty_array.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Concept/_tagged_articles/Grom_Node_has_all_the_required_objects/returns_an_array.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Concept/_tagged_articles/Grom_Node_has_all_the_required_objects/returns_an_array_of_all_tagged_articles.yml, spec/parliament/grom/decorator/concept_spec.rb
* Add decorators for Concept Grom::Node
* Add tests for Concept Grom::Node
* Correct Person decoator variable name from @current_seat_incumbencies to @current_seat_incumbency
* Bumped up version number to 0.16.3
=> GTP - Concept decorators

lib/parliament/grom/decorator.rb, lib/parliament/grom/decorator/answer.rb, lib/parliament/grom/decorator/answering_body_allocation.rb, lib/parliament/grom/decorator/person.rb, lib/parliament/grom/decorator/question.rb, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Answer/_answer_given_date/Grom_Node_has_all_the_required_objects/returns_the_answer_given_date_for_a_Grom_Node_object_of_type_Answer.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Answer/_answer_given_date/Grom_Node_has_no_answer_given_date/returns_nil.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Answer/_answering_person/Grom_Node_has_all_the_required_objects/returns_the_answering_person_for_a_Grom_Node_object_of_type_Answer.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Answer/_answering_person/Grom_Node_has_no_answering_person/returns_nil.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Answer/_text/Grom_Node_has_all_the_required_objects/returns_the_text_for_a_Grom_Node_object_of_type_Answer.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Answer/_text/Grom_Node_has_no_text/returns_an_empty_string.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_AnsweringBodyAllocation/_answering_body/Grom_Node_has_all_the_required_objects/returns_the_answering_body_for_a_Grom_Node_object_of_type_AnsweringBodyAllocation.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_AnsweringBodyAllocation/_answering_body/Grom_Node_has_no_answering_body/returns_nil.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Person/_government_incumbencies/Grom_Node_has_all_the_required_objects/returns_the_government_incumbencies_for_a_Grom_Node_object_of_type_Person.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Question/_answering_body_allocation/Grom_Node_has_all_the_required_objects/returns_the_answering_body_allocation_for_a_Grom_Node_object_of_type_Question.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Question/_answering_body_allocation/Grom_Node_has_no_answering_body_allocation/returns_nil.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Question/_answers/Grom_Node_has_all_th_required_objects/returns_the_answers_for_a_Grom_Node_object_of_type_Question.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Question/_answers/Grom_Node_has_no_answers/returns_an_empty_array.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Question/_asked_at_date/Grom_Node_has_all_the_required_objects/returns_the_asked_at_date_for_a_Grom_Node_object_of_type_Question.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Question/_asked_at_date/Grom_Node_has_no_asked_at_date/returns_nil.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Question/_asking_person/Grom_Node_has_all_the_required_objects/returns_the_asking_person_for_a_Grom_Node_object_of_type_Question.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Question/_asking_person/Grom_Node_has_no_asking_person/returns_nil.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Question/_text/Grom_Node_has_all_the_required_objects/returns_the_text_for_a_Grom_Node_object_of_type_Question.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Question/_text/Grom_Node_has_no_text/returns_an_empty_string.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Question/_uin/Grom_Node_has_all_the_required_objects/returns_the_uin_for_a_Grom_Node_object_of_type_Question.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Question/_uin/Grom_Node_has_no_uin/returns_an_empty_string.yml, spec/parliament/grom/decorator/answer_spec.rb, spec/parliament/grom/decorator/answering_body_allocation_spec.rb, spec/parliament/grom/decorator/question_spec.rb
* Added question decorators
* Added answer decorators
* Added answering body allocation decorators
=> [WEBSITE-2223] Written questions

lib/parliament/grom/decorator/group.rb, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Group/_formal_body_/Grom_Node_also_has_a_type_of_FormalBody/returns_true.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Group/_formal_body_/Grom_Node_does_not_have_a_type_of_FormalBody/returns_false.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Group/_member_count/Grom_Node_has_no_members_count/returns_the_members_count_for_a_Grom_Node_object_of_type_Group.yml, spec/parliament/grom/decorator/group_spec.rb
* Add new method to check if a group is also a formal body
* Modify member_count method and tests to use updated memberCount predicate
=> Updates to Group and FormalBody decorators

lib/parliament/grom/decorator/helpers/date_helper.rb, lib/parliament/grom/decorator/version.rb, spec/parliament/grom/decorator/formal_body_membership_spec.rb, spec/parliament/grom/decorator/government_incumbency_spec.rb, spec/parliament/grom/decorator/incumbency_spec.rb, spec/parliament/grom/decorator/opposition_incumbency_spec.rb, spec/parliament/grom/decorator/seat_incumbency_spec.rb
* Update DateHelper
* Update tests
* Update version number to 0.27.3
=> Amend DateHelper to use full month names

lib/parliament/grom/decorator.rb, lib/parliament/grom/decorator/answer.rb, lib/parliament/grom/decorator/answering_body.rb, lib/parliament/grom/decorator/version.rb, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Answer/_question/Grom_Node_has_no_question/returns_nil.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_Answer/_question/Grom_Node_has_the_required_object/returns_the_question_for_a_Grom_Node_object_of_type_Answer.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_AnsweringBody/_answers/Grom_Node_does_not_have_answers/returns_an_empty_array_for_a_Grom_Node_object_of_type_AnsweringBody.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_AnsweringBody/_answers/Grom_Node_has_answers/returns_the_answers_for_a_Grom_Node_object_of_type_AnsweringBody.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_AnsweringBody/_name/Grom_Node_has_a_name/returns_the_name_for_a_Grom_Node_object_of_type_AnsweringBody.yml, spec/fixtures/vcr_cassettes/Parliament_Grom_Decorator_AnsweringBody/_name/Grom_Node_has_no_name/returns_an_empty_string.yml, spec/parliament/grom/decorator/answer_spec.rb, spec/parliament/grom/decorator/answering_body_spec.rb
- Create Grom::Decorators::AnsweringBody
- Add #question to Grom::Decorators::Answer
- Update version number to 0.27.5
=> Add decorators group_question_written_answered
